# Generated by Django 4.0.2 on 2022-10-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(default='hi', max_length=200),
            preserve_default=False,
        ),
    ]
